default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: root  # MySQL username
  password: "root1"  # MySQL password
  host: localhost

development:
  <<: *default
  database: web_assignment_development

test:
  <<: *default
  database: web_assignment_test

production:
  <<: *default
  database: web_assignment_production
  username: web_assignment
  password: <%= ENV['WEB_ASSIGNMENT_DATABASE_PASSWORD'] %>
